### PR TITLE
xcms-3.6.1

### PR DESCRIPTION
**Pull request by lecorguille**
ping @RJMW

Still need to look at the change at: https://bioconductor.org/packages/release/bioc/news/xcms/NEWS

But at least, the update didn't change the expected results setted in the tests.

### CODE REVIEW

**Comment by lecorguille** [comment]
Changes in version 3.6.1

- [ ] - Fix issue in chromPeakSpectra with method = "signal".
- [ ] - chromPeakSpectra and featureSpectra return now MS2 spectra with an precursor m/z >= mzmin, <= mzmax and retention time >= rtmin, <= rtmax.
- [ ] - Improve performance of chromPeakSpectra and featureSpectra.


Changes in version 3.5.5

- [ ] - Add dirname and dirname<- methods for OnDiskMSnExp to change the path to the raw data files.
- [ ] - Add section "Subset-based alignment" to the xcms vignette to describe the alignment possibility to perform alignments based on a subset of samples (e.g. QC samples).


Changes in version 3.5.4

- [ ] - Fix problem in featureChromatograms with include = "feature_only" that could return a non-valid object.
- [ ] - Ensure that XCMSnExp objects are updated if necessary in all analysis methods.


Changes in version 3.5.3

- [ ] - Fix unit tests.


Changes in version 3.5.2

- [ ] - Small changes in fillChromPeaks,XCMSnExp to reduce memory demand.
- [ ] - Fix issue #359.
- [ ] - Fix issue #360: rawEIC skipped last scan/spectrum if rtrange was provided.
- [ ] - filterMsLevel keeps now chromatographic peaks and feature definitions from the specified MS levels (issue #362).
- [ ] - Fix bug in `xcmsRaw` that leads to a netCDF error message (issue #363).
- [ ] - Add parameter msLevel to chromPeaks for XCMSnExp objects.
- [ ] - Add chromPeakData to allow adding arbitrary annotation to chromatographic peaks.
- [ ] - Change default of parameter value in featureValues from value = "index" to value = "into".
- [ ] - Add parameter isFilledColumn to chromPeaks allowing the old behaviour to include the is_filled column in the chromatographic peak matrix.


Changes in version 3.5.1

- [ ] - Fix issue #349.
- [ ] - Add updateObject function for XCMSnExp objects (issue #347).
- [ ] - Add dropFilledChromPeaks methods for XChromatogram and XChromatograms objects.
- [ ] - Add parameter filled = FALSE to chromatogram and featureChromatograms functions.
- [ ] - Fix matchedFilter peak detection problems with empty spectra (issue #325).
- [ ] - featureChromatograms extracts by default only chromatographic peaks associated with a feature.
- [ ] - chromatogram,XCMSnExp extracts an XChromatogram containing also chromatographic peaks and feature definitions.
- [ ] - Add featureValues method for XChromatograms objects (issue #336).
- [ ] - Add correspondence analysis (peak grouping) for chromatographic data (for now only with PeakDensity method; issue #336).
- [ ] - Add featureDefinitions slot to XChromatograms object and related accessor methods.
- [ ] - Add subset alignment option subsetAdjust = "average" to adjust left-out samples (blanks or simply non-subset samples) based on an interpolation from the results of the previous and subsequent subset sample.
- [ ] - Add parameter subsetAdjust to PeakGroupsParam allowing to switch between different methods to adjust samples left out in the alignment process.
- [ ] - Alignment based on a sample subset for the peak groups method (issue #335): sample subset can be defined with the subset parameter, samples not included in the subset will be aligned based on the adjusted retention times of the closest sample in the subset.
- [ ] - Add findChromPeaks,XChromatograms (issue #332).
- [ ] - Add processHistory,XChromatograms.
- [ ] - Add plot,XChromatograms method with automatic peak highlighting (issue #334).
- [ ] - Add hasChromPeaks,XChromatograms method.
- [ ] - Add XChromatograms class with constructor function and coercing method.
- [ ] - Add hasChromPeaks,XChromatogram method.
- [ ] - Add filterRt,XChromatogram, filterMz,XChromatogram.
- [ ] - Add plot,XChromatogram function supporting of highlighting/drawing identified chromatographic peaks.
- [ ] - findChromPeaks,Chromatogram returns an XChromatogram object (issue #329).
- [ ] - Add chromPeaks,XChromatogram (issue #329).
- [ ] - Add XChromatogram object (issue #329).
- [ ] - Fix higlightChromPeaks with type = "polygon": peak filling represents now the full detected peak and is no longer cut by the provided rt.
- [ ] - Add argument peakIds to highlightChromPeaks allowing to specify the IDs of peaks to be highlighted.
- [ ] - Add example on clustering of base peak chromatograms to the vignette (issue #328).
- [ ] - Small fix in the vignette (issue #327).
- [ ] - Add parameter groupval to exportMetaboAnalyst (issue #296).
- [ ] - Fix bug in show,XCMSnExp that would throw an error if no process history is present.

**Comment by RJMW** [comment]
ping @andzajan - FYI

**Comment by lecorguille** [comment]
What do you think about this new parameters ?
https://rdrr.io/bioc/xcms/man/adjustRtime-peakGroups.html
 - subset
 - subsetAdjust

**Comment by andzajan** [comment]
> What do you think about this new parameters ?
> https://rdrr.io/bioc/xcms/man/adjustRtime-peakGroups.html
> 
> * subset
> * subsetAdjust
>   I guess that it will be tricky to fill "indices of sample" disappointed

I am not convinced these are important fo the moment, regarding sample indices that must be implemented in rtcorr tool, as it allows to specify which sample to use for refrence alignment.

**Comment by lecorguille** [comment]
I can imagine that implementing https://rdrr.io/bioc/xcms/man/exportMetaboAnalyst.html can be interesting?
But is it mandatory for the xcms updating or can we just suggest that in an issue?

**Comment by andzajan** [comment]
**Get the Peak List** from **xcms groupChromPeaks** does provide outputs which are easy to submit to MetaboAnalyst already. I would say it's not urgent to implement this export function.

**Comment by lecorguille** [comment]
So, do you see anything that seem important for you in those changes?
 - new paramaters
 - new functions
?

**Comment by lecorguille** [comment]
Damn!
I need to update my test-data. The RData came from a too old version of xcms
```
|  Error in `rownames<-`(`*tmp*`, value = rownames(chromPeaks(new_x))) :
|  attempt to set 'rownames' on an object with no dimensions
|  Calls: mergeXData ... c -> c.XCMSnExp -> .concatenate_XCMSnExp -> rownames<-
```

**Comment by lecorguille** [comment]
plot_chromatogram still have trouble.
Should be around the new object XChromatograms?
I may will have to update a last RData

**Comment by andzajan** [comment]
It looks like there is another issue as well, **xcms findChromPeaks** tool doesn't recognise output from **MSnBase readMSData** tool.

**Comment by lecorguille** [comment]
xref: https://github.com/sneumann/xcms/issues/444
I will keep xcms 3.4.4 for the plot_chromatogram tool.

**Comment by lecorguille** [comment]
GREEEN

**Comment by lecorguille** [comment]
@andzajan What did you mean by:
> It looks like there is another issue as well, xcms findChromPeaks tool doesn't recognise output from MSnBase readMSData tool.

**Comment by lecorguille** [comment]
I will also try to fix that https://github.com/workflow4metabolomics/tools-metabolomics/issues/164 quickly before a release

**Comment by lecorguille** [comment]
It's still green.
It addresses a couple of issue.
So for me, this PR is ready for a review.

I'm aware that it's a relative big boy. I'm still trying to simplify the wrappers as much as possible and reduce the number of R functions.

**Comment by lecorguille** [comment]
Oki, so no news, good news.
Viva the auto-merge 👿

**Pull request merged**
