### PR TITLE
Add maintainer list to README

### PR DESCRIPTION
**Pull request by bernt-matthias**
Mainly this documents the list of members with commit access in the README and outlines a procedure for adding new members. So far I just added a few of the people which are currently in (judging from recent PRs). Feel free to finish the list.

Open for discussion ping @bgruening @yguitton @hechth @lecorguille 

Would be a good point to discuss further rules if desired? For instance are special rules regarding approval wanted for tools from W4M? We could try to organize this via the code owner file.

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by yguitton — CHANGES_REQUESTED** [review]
Hi @bernt-matthias 

Thanks for your contribution,
There are some typos to adress at lines 53-55

Best 
Yann

**Comment by melpetera** [comment]
Hi,

Good idea here, thanks for the work.

About the team members, to note @Lain-inrae is changing job the 1st of October (if I am not wrong with the dates), leaving the metabolomics field for new horizons. May be wise to ask her if she wants to remain in the maintaining group first.

**Comment by lecorguille** [comment]
> About the team members, to note @Lain-inrae is changing job the 1st of October (if I am not wrong with the dates), leaving the metabolomics field for new horizons. May be wise to ask her if she wants to remain in the maintaining group first.

I can say that no, she doesn't want to remain in the maintainers

**Review by lecorguille — APPROVED** [review]

**Comment by lecorguille** [comment]
@yguitton Is this PR ok for you?

**Comment by yguitton** [comment]
Yes all seems good you can merge

**Review by bgruening — APPROVED** [review]

**Pull request merged**
