### PR TITLE
rename .name to .element_identifier

### PR DESCRIPTION
**Pull request by bernt-matthias**
for the remaining tools

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bernt-matthias** [comment]
> Remove the r-linter ;)

We have to restist this impulse :)  linters are less annoying than ugly inconsistent code.

**Comment by lecorguille** [comment]
Hey, ipo was integreted before the arrival of the r-linter 😇

**Comment by lecorguille** [comment]
If I merge now, do you know if the "Check file sizes" will be an issue for the publishing in the TS?

**Comment by bgruening** [comment]
Ship it? Or not?

**Comment by bernt-matthias** [comment]
Seems that this was not deployed: https://github.com/workflow4metabolomics/tools-metabolomics/actions/runs/6115157809

ipo4xcmsSet fails with 

```
Error in ipo4xcmsSet(directory, "IPO_parameters4xcmsSet.tsv", args, samplebyclass) : 
  object 'peakpicking_best_params' not found
Execution halted
```

There is also a warning, but likely unrelated

```
rror in plot.new() : could not open file '../IPO_results/rsm_1.jpg'
In addition: Warning message:
In dir.create(subdir) :
  cannot create dir '../IPO_results', reason 'Read-only file system'
Error in plotting (see above), but IPO continues to work normally!
```

**Comment by bernt-matthias** [comment]
I opened three new PR. The first should fix the IPO bug. The other two just add a bugus change to trigger deployment. 

Guess having independent PRs makes deployment easier.

**Pull request merged**
