### PR TITLE
Change physiofit category

### PR DESCRIPTION
**Pull request by llegregam**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

### CODE REVIEW

**Comment by llegregam** [comment]
@yguitton @lecorguille @bgruening I do not understand the error returned during the checks. Any ideas?

**Comment by bgruening** [comment]
@llegregam the CI integration changed. The R linter has some breaking changes. I tried to fix that in the latest commit.

**Comment by llegregam** [comment]
> @llegregam the CI integration changed. The R linter has some breaking changes. I tried to fix that in the latest commit.

Seems to have worked! Thanks :)

**Comment by llegregam** [comment]
@bgruening @lecorguille @yguitton Please review :)

**Comment by lecorguille** [comment]
Thanks @bgruening

**Pull request merged**
