### PR TITLE
Bump to 3.3.4

### PR DESCRIPTION
**Pull request by llegregam**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-metabolomics/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
grafik

**Comment by llegregam** [comment]
> grafik

I'm working on it ^^'

**Comment by llegregam** [comment]
@bgruening tests have passed, apparently they were failing because I hadn't finished updating the tool on bioconda :)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks a lot!

**Pull request merged**
